### ISSUE TITLE
version 255.255 is unsupported

### ISSUE THREAD

**Issue by ProgrammerPro500** [jflight-public/jesc-configurator#20]
Hi. I have 4in1 ESC (G-H-15). While it update by jesc-configurator, i get a message: "version 255.255 is unsupported", bat one of four ESC is OK! What can i do?
[Log.txt](https://github.com/jflight-public/jesc-configurator/files/4000852/Log.txt)

**Comment by ProgrammerPro500** [comment]
Bingo! I have shooted this trouble self. Reinstall the original firmware, after update ESC again with jesc-configurator. All start working properly! Sorry for my English : )

**Comment by Sankar27104** [comment]
heyy, i am facing the same problem, and i am very new to this work. could you please share the exact steps to overcome this problem.

**Comment by Sankar27104** [comment]
heyy, i am facing the same problem, and i am very new to this work. could you please share the exact steps to overcome this problem.
