### ISSUE TITLE
Your jflight.net website is down.

### ISSUE THREAD

**Issue by Anbuise** [jflight-public/jesc-configurator#21]
Your jflight.net website is down.

**Comment by ghostface** [comment]
Works fine for me (at least now)

**Comment by joelucid** [comment]
Yeah it was down for about 2 h. Sorry.

**Comment by Anbuise** [comment]
It's all good. Thanks for everything you do for our community!On Jan 6, 2020 11:40 AM, joelucid <notifications@github.com> wrote:Yeah it was down for about 2 h. Sorry.
