### ISSUE TITLE
lost 3 ESC after some flashing

### ISSUE THREAD

**Issue by ThLehmann** [jflight-public/jesc-configurator#27]
hello,

just want to update my O-H-5 ESC from a BetaFPV meteor65 to JESC. After flashing to V2.2 i could'nt licence the ESC's because the button stays unaccessable. So i tryed out the other ones, V2.3 for H version, back to V2.2 48/24kHz. The licence button does'nt came activ.
So i wanna check my new copter without RPM filtering .... But now only one motor is activ, hmm.
Back to JESC and BLHeliSuite i noticed that only ESC #3 is available, all other ones are lost :(
Don'nt know what happend
Hope you can give a solution for this behaviour.
Thomas
[Log.txt](https://github.com/jflight-public/jesc-configurator/files/4093934/Log.txt)

**Comment by ThLehmann** [comment]
![ESCerr](https://user-images.githubusercontent.com/34693823/72848805-adb7dd80-3ca5-11ea-9b3d-c4bf77b880e7.png)

**Comment by ThLehmann** [comment]
![JESC2](https://user-images.githubusercontent.com/34693823/72848883-d213ba00-3ca5-11ea-8f88-97604e6151a8.png)

**Comment by joelucid** [comment]
Your log only shows the failed attempts to communicated with the esc, no flashing. Can you send the full debug log, please?

**Comment by ThLehmann** [comment]
I thought that it was the full log. What else i should do to get the full log ? Sorry for my unknownless

**Comment by joelucid** [comment]
Just using the "Save Debug Log" button should do the trick. You need to do it on the machine you used for flashing.

**Comment by ThLehmann** [comment]
Ok, made three Logs
after connecting (the one you need?)
after reading setup
after flashing ESC 2+4
[LogAfterConnect.txt](https://github.com/jflight-public/jesc-configurator/files/4107373/LogAfterConnect.txt)
[LogAfterReadSetup.txt](https://github.com/jflight-public/jesc-configurator/files/4107372/LogAfterReadSetup.txt)
[LogAfterFlashing2-4.txt](https://github.com/jflight-public/jesc-configurator/files/4107371/LogAfterFlashing2-4.txt)

**Comment by joelucid** [comment]
All of these logs already have at least two escs that don't get detected. The log doesn't get deleted by jesc-configurator so any debug log you save on a machine should contain everything you've done on that machine.

Have you ever seen all escs in configurator? If so can you send me the log from the machine on which you did the initial flash?

**Comment by ThLehmann** [comment]
the log is from that machine, and yes all four ESC were seen and could be flashed. I only go on with flashing some other versions because the licence button was not coming available. See my entry post.
The error happens as my battery goes empty i think.
before i open this issue i didnt save any log, the log in first thread was the first one on this machine.
So i am wondering why the log is/should be empty.

**Comment by joelucid** [comment]
YEah - no clue really. All I can do is refer you to https://github.com/jflight-public/jesc-configurator/issues/41 for a pointer to how to flash escs using the c2 interface.
