### ISSUE TITLE
ignore inappropriate MCU cant pass the flash all step

### ISSUE THREAD

**Issue by DarkF4lcon** [jflight-public/jesc-configurator#3]
[Log.txt](https://github.com/jflight-public/jesc-configurator/files/3741064/Log.txt)

Cant pass the step flash all

**Comment by joelucid** [comment]
It looks like this is a L style esc which isn't supported in JESC. Could you read setup in blhelis-configurator and send a screenshot?

**Comment by DarkF4lcon** [comment]
Here it is

What can i do?

![IMG_20191018_221516](https://user-images.githubusercontent.com/56699021/67128936-169a4000-f1f5-11e9-8526-b7e1c53d1a35.jpg)
![IMG_20191018_221441](https://user-images.githubusercontent.com/56699021/67128938-169a4000-f1f5-11e9-9cdc-23e62fb2e078.jpg)

**Comment by joelucid** [comment]
Could you try to reflash these to 16.7 in blheli configurator let me know if that works. If it does then retry to flash jesc.

**Comment by DarkF4lcon** [comment]
Reflashed the escs but it doesnt work neither
Is it possible to reset my licences for me to try on my other drone?
I have a 4in1 esc from Mamba on the other one

**Comment by joelucid** [comment]
Ok - with the escs flashed back to blhelis A-H-20 please try to flash jesc again and then post the jesc-configurator log.

**Comment by DarkF4lcon** [comment]
[Log.txt](https://github.com/jflight-public/jesc-configurator/files/3849111/Log.txt)
Here it is, Reflashed the ESCs again, Still nothing to select after clicking on Flash all in JESC

**Comment by joelucid** [comment]
Ok - the signature returned by the boot loader of the esc is 0xe8b1:
```
Uncaught Error: Unknown MCU signature: e8b1 chrome-extension://maigancljkhnkhpejlfmgjjmjafafdhp/js/build/firmware_selector.js 26 13 Error: Unknown MCU signature: e8b1
```

This signature is used by L style escs only which jesc does not support. On the other hand the layout tag A-H-20 suggests it is a H style esc. One of the two is clearly wrong.

Could you please identify the type of cpu on the esc? Make a pic of the esc at a high resolution  and angle that the chip markings can be seen and post it here. What brand/model of esc is this?

If it is in fact an H style esc with the efm8bb21 you would likely need to patch the bootloader to fix it. This could be done by flashing the escs with jesc or blhelis using the c2 interface. The normal bootloader interface jesc-configurator uses protects against modifying the bootloader for obvious reasons.

**Comment by DarkF4lcon** [comment]
![IMG_20191115_075601](https://user-images.githubusercontent.com/56699021/68926968-9973d380-077e-11ea-97a1-7e47b42ce6b8.jpg)
![IMG_20191115_080334](https://user-images.githubusercontent.com/56699021/68926969-9973d380-077e-11ea-8526-a7e1a3a8a100.jpg)
Thanks for the reply

Heres the photos of the esc type that i use in this drone.
Says BB21 and its a Racestar MS25A

What can i do to revert this situation?

Thanks

**Comment by joelucid** [comment]
Yeah it's definitely a bb21 with incorrectly flashed bootloader. I've made a change to the server side configuration of jesc-configurator to allow this one to be flashed as well. Could you try again. please?

**Comment by DarkF4lcon** [comment]
Hi there

It worked, thanks for fixing this situation

Thanks

**Comment by joelucid** [comment]
Great @darkf4icon! Glad we got it sorted out!
