### ISSUE TITLE
will not connect to F3 with BF4.0.6

### ISSUE THREAD

**Issue by LowLifeFPV** [jflight-public/jesc-configurator#36]
Using SPRACINGF3EVO with BF4.0.6, JESC will not connect. JESC says "Connection failed, ensure that you have selected the correct port or restart your device." would like to run 48K and was going to progress with F3 Performace Edition once ESC is flashed. ESC is P-H-10. Definetly selecting right port. Using same Comm port I use to connect with BF.

**Comment by joelucid** [comment]
Can you connect with BLHeli configurator?

**Comment by LowLifeFPV** [comment]
It would still connect with blheli suite but not with blheli or JESC configurator . I have since flashed the board with the F3 performance edition of 4.1.1 and it connects again.

**Comment by joelucid** [comment]
Nice!
