### ISSUE TITLE
JESC-configurator can't talk to ESC #1 and #4

### ISSUE THREAD

**Issue by WPS-RPAS** [jflight-public/jesc-configurator#38]
@joelucid 
[meteor65Log.txt](https://github.com/jflight-public/jesc/files/4196412/meteor65Log.txt)

**Comment by joelucid** [comment]
I'm creating new overview issues so we can keep discussion in one place. https://github.com/jflight-public/jesc-configurator/issues/42 is the issue for this type of problem. Please continue discussion there.
