### ISSUE TITLE
Flash Failed After Multiple Attempts

### ISSUE THREAD

**Issue by jparrr** [jflight-public/jesc-configurator#39]
Board: S411

Unable to successfully flash. Debug log attached. 
[Log.txt](https://github.com/jflight-public/jesc/files/4189638/Log.txt)

**Comment by joelucid** [comment]
I'm reorganizing all issues to provide better overview. This one is now a duplicate to the overview issue https://github.com/jflight-public/jesc-configurator/issues/41. Please continue discussion there.
