### ISSUE TITLE
flashing jesc problem

### ISSUE THREAD

**Issue by overdrive86** [jflight-public/jesc-configurator#61]
i've installed the free 2.2 48khz jesc on my 4 in 1 hobbywing 4 in 1 esc and all was good.
i bought a license for 4 esc and tryed to upgrade to the 2.3 24 khz rpm version, activated the license and when i flas all with the correct version of esc there is a problem and don't start flashing.
in attachment the file log. i also tried to go back to blheli and i can flash blheli but i can't flash jesc anymore, not even the free version(log3)
[Log.txt](https://github.com/jflight-public/jesc-configurator/files/4640067/Log.txt)
[Log3.txt](https://github.com/jflight-public/jesc-configurator/files/4640076/Log3.txt)

**Comment by joelucid** [comment]
You need to install BF >= 4.1 to flash licensed jesc on an esc.
