### ISSUE TITLE
Where are the buttons

### ISSUE THREAD

**Issue by mikespas123** [jflight-public/jesc-configurator#62]
Windows 64x - downloaded 1.2.8

Connected the drone and the program read the file but the rest of the buttons don't show and the buttons at the bottom are grayed out..

Help pls

![2020-05-20 19_00_55-JESC Configurator](https://user-images.githubusercontent.com/65688283/82505900-6531f480-9acc-11ea-908c-8b452fd7f8ab.png)
[Log.txt](https://github.com/jflight-public/jesc-configurator/files/4659666/Log.txt)

**Comment by joelucid** [comment]
From the log it this isn't a blheli_s esc. JESC only runs on blheli_s escs.
