### ISSUE TITLE
my licensed esc's will not flash

### ISSUE THREAD

**Issue by BlueDragonBlade76** [jflight-public/jesc-configurator#68]
I tried flashing two quads with licensed esc's and the flashing process starts but does not update and moves onto next esc
[Log.txt](https://github.com/jflight-public/jesc-configurator/files/4925393/Log.txt)

**Comment by joelucid** [comment]
You need to install betaflight >= 4.1 to flash the telemetry service.

**Comment by BlueDragonBlade76** [comment]
Thank you very much!

Sent from my iPhone

On Jul 17, 2020, at 5:26 AM, joelucid <notifications@github.com> wrote:

﻿

You need to install betaflight >= 4.1 to flash the telemetry service.
