### ISSUE TITLE
no read setup button on ubuntu

### ISSUE THREAD

**Issue by fractalfederation** [jflight-public/jesc-configurator#7]
downloaded 1.2.5 and ran, it loads fine, able to connect but there is no read setup write setup buttons at bottom. only error i see in terminal is:

[29237:29237:1105/114454.969897:ERROR:component_loader.cc(165)] Failed to parse extension manifest.

not sure if its related.

**Comment by TheIsotopes** [comment]
> downloaded 1.2.5 and ran, it loads fine, able to connect but there is no read setup write setup buttons at bottom.

same with both windows versions :( 

@joelucid can you check whats wrong.

**Comment by joelucid** [comment]
I will look into it. Thanks for reporting!

**Comment by joelucid** [comment]
@fractalfederation, @TheIsotopes which operating systems did you use?

**Comment by Burnich** [comment]
Same problem on Windows 10 64 bit version

**Comment by Burnich** [comment]
Same problem on Windows 10 64 bit version

> downloaded 1.2.5 and ran, it loads fine, able to connect but there is no read setup write setup buttons at bottom. only error i see in terminal is:
> 
> [29237:29237:1105/114454.969897:ERROR:component_loader.cc(165)] Failed to parse extension manifest.
> 
> not sure if its related.

Same problem on Windows 10 64bits version

**Comment by TheIsotopes** [comment]
@joelucid using Windows 10 (1909 - 64bit)

**Comment by Burnich** [comment]
I tried all the versions of the configurator (from 1.2.0 to 1.2.5) on Windows 10 64bit. Always the same result : I can connect but no read button...

**Comment by joelucid** [comment]
Ok - downloaded a Windows 10 64bit VM and I can reproduce it.

**Comment by fractalfederation** [comment]
ubuntu 18.04

**Comment by joelucid** [comment]
These issues should now be solved.

**Comment by fractalfederation** [comment]
built on ubuntu 18.04 and working! thanks

**Comment by TheIsotopes** [comment]
> These issues should now be solved.

@joelucid can you release a new build to test this on windows 10

**Comment by Burnich** [comment]
> > These issues should now be solved.
> 
> @joelucid can you release a new build to test this on windows 10

No need ! In my case I just re-download the 1.2.5 version after @joelucid last post and everything was fix !

**Comment by joelucid** [comment]
@TheIsotopes you don't even need to update. I did respond 1.2.5 but the file where the error was is first attempted to download from jflight.net so I could just patch it there.
