### ISSUE TITLE
Website down?

### ISSUE THREAD

**Issue by chenrymotorsports** [jflight-public/jesc-configurator#74]
Hi, I purchased credits yesterday and was able to flash one set of my esc's but upon attemting to do my next couple, found that the website is down so the Jesc application cannot verify credit purchase and allow license of the remaining esc's. Attached is a failure log. Im not sure how else to contact. Thanks!

[froze during licensing.txt](https://github.com/jflight-public/jesc-configurator/files/5085011/froze.during.licensing.txt)

**Comment by joelucid** [comment]
Now fixed
