### ISSUE TITLE
Same issue using Windows 7

### ISSUE THREAD

**Issue by blheliFan** [jflight-public/jesc-configurator#8]
Im using Windows 7 64bit OS. My esc is hakrc 40A. Done flashing esc firmware jesc G40 48 2.2. Hex and g40 24 2.2 hex. But the configurator jesc still not read no menu.. 

![IMG_20191108_124830](https://user-images.githubusercontent.com/57511861/68450869-7f3e7080-0227-11ea-93df-e0fbd8ed065a.jpg)

**Comment by blheliFan** [comment]
Im using Windows 7 64bit OS. My esc is hakrc 40A. Done flashing esc firmware jesc G40 48 2.2. Hex and g40 24 2.2 hex. But the configurator jesc still not read no menu.. 
![Uploading IMG_20191108_124830.jpg…]()
![Uploading IMG_20191108_124830.jpg…]()

**Comment by blheliFan** [comment]
Im using Windows 7 64bit OS. My esc is hakrc 40A. Done flashing esc firmware jesc G40 48 2.2. Hex and g40 24 2.2 hex. But the configurator jesc still not read no menu.. 
![IMG_20191108_124830](https://user-images.githubusercontent.com/57511861/68450762-1eaf3380-0227-11ea-8830-690a60699979.jpg)

**Comment by blheliFan** [comment]
Im using Windows 7 64bit OS. My esc is hakrc 40A. Done flashing esc firmware jesc G40 48 2.2. Hex and g40 24 2.2 hex. But the configurator jesc still not read no menu.. 
![IMG_20191108_124830](https://user-images.githubusercontent.com/57511861/68450848-6766ec80-0227-11ea-8c27-1d55c54e4b0e.jpg)

**Comment by joelucid** [comment]
This is now fixed, right @blheliFan? There was a short period where a server was misconfigured causing this.
