### ISSUE TITLE
After flashing cannot update telemetry

### ISSUE THREAD

**Issue by michael-blue2** [jflight-public/jesc-configurator#9]
I updated to 2.2 24kz and the button to update the telemetry is not available to press 

![image](https://user-images.githubusercontent.com/25118311/68526565-21bd2900-02e6-11ea-90f9-f4e88e3daa66.png)

**Comment by joelucid** [comment]
You need to license the escs using the "License All" button before flashing Telemetry as pointed out in the green notice.
